import Link from 'next/link'
import { ArrowRight, Bell, ChevronRight, Clock3, Play, Sparkles, Trophy } from 'lucide-react'
import { AcademyShell, CourseArtwork } from '@/components/academy-shell'
import { course, courseProgress, sectionOf, totalDuration } from '@/data/platform'
import { getSession } from '@/lib/central'
import { CourseCard } from '@/components/course-card'

function progressMessage(percent: number) {
    if (percent === 0) return ['Vamos começar?', 'Assista à primeira aula para iniciar sua formação.']
    if (percent === 100) return ['Parabéns!', 'Você concluiu todas as aulas do curso.']
    if (percent >= 50) return ['Muito bem!', 'Você já completou mais da metade.']
    return ['Bom começo!', 'Continue de onde parou e mantenha o ritmo.']
}

export default async function Page() {
    const { user, completedLessonIds } = await getSession()
    const progress = courseProgress(completedLessonIds)
    const [title, subtitle] = progressMessage(progress.percent)
    const nextSection = progress.next ? sectionOf(progress.next.id) : null
    const nextIndex = progress.next && nextSection ? nextSection.lessons.indexOf(progress.next) : -1
    return <AcademyShell><div className="flex flex-col gap-9">
        <section className="flex flex-col justify-between gap-5 md:flex-row md:items-end"><div><p className="mb-2 flex items-center gap-2 text-sm font-medium text-[#0098d8]"><Sparkles className="size-4" /> {user ? `Olá, ${user.name.split(' ')[0]}` : 'Olá'}</p><h1 className="text-3xl font-semibold tracking-[-.03em] text-[#0c1428] md:text-4xl">Continue sua jornada de formação.</h1><p className="mt-2 text-[#718096]">Cada aula aproxima você do próximo nível.</p></div><button className="flex h-10 w-fit items-center gap-2 rounded-xl border border-[#e1e9f0] bg-white px-4 text-sm font-medium text-[#52647a] hover:bg-[#f7fafc]"><Bell className="size-4" /> Novidades</button></section>
        <section><div className="relative overflow-hidden rounded-2xl bg-[#0c1428] p-6 text-white md:p-8"><div className="absolute right-[-70px] top-[-100px] size-72 rounded-full border-[34px] border-[#0098d8]/20" /><div className="relative flex flex-col justify-between gap-8 md:flex-row"><div><p className="text-xs font-semibold uppercase tracking-[.17em] text-[#80d8f2]">Seu progresso</p><h2 className="mt-3 text-2xl font-semibold">{course.title}</h2><p className="mt-2 max-w-md text-sm leading-relaxed text-white/60">{course.description}</p><div className="mt-7 flex items-center gap-4"><div className="relative size-20 rounded-full" style={{ background: `conic-gradient(#1db1e7 ${progress.percent * 3.6}deg, rgba(255,255,255,.12) 0deg)` }}><div className="absolute inset-2 grid place-items-center rounded-full bg-[#0c1428] text-lg font-semibold">{progress.percent}%</div></div><div><p className="text-sm font-medium">{title}</p><p className="mt-1 text-xs text-white/50">{subtitle}</p></div></div></div><div className="grid grid-cols-2 gap-x-8 gap-y-5 self-end md:min-w-[240px]"><div><p className="text-2xl font-semibold">{progress.completed}</p><p className="mt-1 text-xs text-white/50">Aulas concluídas</p></div><div><p className="text-2xl font-semibold">{progress.remaining}</p><p className="mt-1 text-xs text-white/50">Aulas restantes</p></div><div><p className="text-2xl font-semibold">{progress.total}</p><p className="mt-1 text-xs text-white/50">Aulas no curso</p></div><div><p className="text-2xl font-semibold">{totalDuration()}</p><p className="mt-1 text-xs text-white/50">Duração total</p></div></div></div></div></section>
        <section><div className="mb-5 flex items-end justify-between"><div><p className="mb-1 text-xs font-semibold uppercase tracking-[.15em] text-[#0098d8]">Próxima aula</p><h2 className="text-xl font-semibold tracking-tight">{progress.completed ? 'Continue de onde parou' : 'Comece por aqui'}</h2></div><Link href={`/treinamentos/${course.id}`} className="hidden items-center gap-1 text-sm font-semibold text-[#007eae] hover:text-[#005a7d] sm:flex">Ver treinamento <ChevronRight className="size-4" /></Link></div><div className="grid overflow-hidden rounded-2xl border border-[#e4ebf1] bg-white md:grid-cols-[280px_1fr]"><CourseArtwork tone={course.tone} accent={course.accent} title="" /><div className="flex flex-col justify-between gap-5 p-6 md:p-7">{progress.next ? <><div><div className="flex items-center justify-between gap-4"><span className="text-xs font-semibold uppercase tracking-[.12em] text-[#0098d8]">{nextSection?.title} · Aula {String(nextIndex + 1).padStart(2, '0')} de {nextSection?.lessons.length}</span><span className="hidden text-xs text-[#8290a3] sm:block">{progress.percent}% concluído</span></div><h3 className="mt-3 text-xl font-semibold tracking-tight">{progress.next.title}</h3><p className="mt-2 text-sm text-[#718096]">{course.title}</p></div><div><p className="flex items-center gap-1.5 text-xs text-[#8290a3]"><Clock3 className="size-3.5" /> {progress.next.duration}</p><Link href={`/treinamentos/${course.id}/aula/${progress.next.id}`} className="mt-5 inline-flex h-10 items-center gap-2 rounded-xl bg-[#0098d8] px-4 text-sm font-semibold text-white hover:bg-[#0087c0]">{progress.completed ? 'Continuar aula' : 'Começar curso'} <Play className="size-4 fill-current" /></Link></div></> : <div className="flex items-center gap-4"><div className="grid size-12 place-items-center rounded-xl bg-[#e6f7f1] text-[#16846b]"><Trophy className="size-6" /></div><div><h3 className="text-xl font-semibold tracking-tight">Curso concluído</h3><p className="mt-1 text-sm text-[#718096]">Você assistiu a todas as aulas.</p></div></div>}</div></div></section>
        <section><div className="mb-5 flex items-end justify-between"><div><p className="mb-1 text-xs font-semibold uppercase tracking-[.15em] text-[#0098d8]">Sua biblioteca</p><h2 className="text-xl font-semibold tracking-tight">Meus treinamentos</h2></div><Link href="/meus-treinamentos" className="flex items-center gap-1 text-sm font-semibold text-[#007eae]">Ver todos <ArrowRight className="size-4" /></Link></div><div className="grid gap-5 md:grid-cols-2 xl:grid-cols-3"><CourseCard percent={progress.percent} /></div></section>
    </div></AcademyShell>
}
